apiVersion: v1 
kind: Service 
metadata:
  name: weatherapp-weather-svc 

spec:
  type: ClusterIP 
  ports:
    - name: http-service 
      port: 5000
      targetPort: http 
      protocol: TCP 
  selector:
    api.kubernetes.io/name: weatherapp-weather