apiVersion: apps/v1
kind: Deployment 
metadata:
  name: weatherapp-ui

spec:
  replicas: 2 
  selector:
    matchLabels:
      api.kubernetes.io/name: weatherapp-ui 

  template:
    metadata:
      labels:
        api.kubernetes.io/name: weatherapp-ui

    spec:
      containers:
        - name: weatherapp-ui 
          image: afakharany/weatherapp-ui:lab
          imagePullPolicy: IfNotPresent
          env:
            - name: AUTH_HOST 
              value: weather-app-svc
            - name: AUTH_PORT 
              value: "8080"
            - name: WEATHER_HOST 
              value: weatherapp-weather-svc
            - name: WEATHER_PORT 
              value: "5000"
          ports:
            - name: http 
              containerPort: 3000
              protocol: TCP 

          livenessProbe:
            httpGet:
              path: /health 
              port: http

          readinessProbe:
            httpGet:
                path: /health 
                port: http

